Add Approval CRD
jwkim1993/approval-operator pull request #4
Opened 2020-06-25 05:31 UTC by jwkim1993

## Done
- Add structure to create Approval CRD
- Devide condition type, because it will be replaced with knative's

## TO DO
- Implement test code for validating CRD

2020-06-25 07:23 UTC, cqbqdd11519 requested changes
* Golang에서는 tab(\t)이 indentation 표준인 것 같습니다 (https://golang.org/doc/effective_go.html#formatting)
`go fmt` 명령어 쓰면 알아서 포맷팅 되니까 커밋 전에 실행하면 좋을 것 같습니다
* `operator-sdk generate k8s`명령이랑 `operator-sdk generate crds` 명령으로 CRD 파일이랑 zz_generated.deepcopy.go 파일도 생성해서 추가해주세요

2020-06-25 07:23 UTC, cqbqdd11519 commented on pkg/apis/tmax/v1/approval_types.go
> +	Status ApprovalStatus `json:"status"`
Status 필드가 필수값이 되면 create 시 validation을 통과하지 못하지 않을까요?
Tekton이나 JenkinsX등 참조해보니까 spec과 status에는 omitempty를 넣는 것이 일반적인 것 같습니다

2020-06-25 11:37 UTC, jwkim1993 commented
generation 되는 파일은 부산물이라서 일부러 추가하지 않았는데, 추가하는게 좋을까요?? 추가하는 프로젝트도 있고, 아닌 프로젝트도 있어서 저는 추가하지는 않았습니다

2020-06-25 11:40 UTC, jwkim1993 commented
탭으로 정렬했었는데 이상하네요. 말씀하신 fmt 적용해서 다시 적용하겠습니다.

2020-06-25 16:05 UTC, cqbqdd11519 commented
제가 알기로는 `operator-sdk generate k8s`로 생성되는 zz_generated.deepcopy.go 파일은 단순한 부산물이라기보다는 runtime.Object 인터페이스에 정의된 deepcopy 함수들을 구현해놓은 파일이라 추후 controller나 webhook 또는 다른 프로젝트에서 Approval 객체를 k8s client 모듈을 사용해 CRUD할 때 필수적인 파일로 알고있습니다

`operator-sdk generate crds`로 생성되는 CRD 파일들의 경우 이미 프로젝트에 initial commit으로 추가돼있기도 하고 추후 Approval operator 설치 가이드 등을 작성할 때를 대비해서 deploy/ 디렉토리에 오퍼레이터를 설치할 때 필요한 모든 yaml을 최신 버전으로 유지하는 게 좋지 않을까 싶습니다

2020-06-26 01:09 UTC, jwkim1993 commented
go.sum과 go.mod도 commit하는것이 좋을것 같습니다.
(Ref: https://www.reddit.com/r/golang/comments/97dxj1/should_i_add_the_gosum_file_to_the_repo_of_a/e47m38p/)

2020-06-29 00:36 UTC, merged